### ISSUE TITLE
Non symmetric API?

### ISSUE THREAD

**Issue by carl-mastrangelo** [google/census-java#35]
The serialization and deserialization of a Census Context seems to be split across two classes instead of one:  CensusContextFactory.deserialize and CensusContext.serialize.  Why have them in separate places?

**Comment by zhangkun83** [comment]
Because `deserialize()` creates a CensusContext, it doesn't fit into CensusContext, unless it were static, which we wouldn't like.

**Comment by sebright** [comment]
`serialize()` is in `CensusContext` so that we don't have to increase the visibility of the context's internal representation.  `deserialize()` is in `CensusContextFactory` so that it can be polymorphic.  I don't know of a way to put them in the same class, though that would be more convenient.
